name: Publish Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/gsandf/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            
    - name: Install Dependencies
      run: dotnet restore

    - name: Build Nuget Package
      run: dotnet pack -p:PackageVersion=${{github.event.release.tag_name}} -p:PackageId=Gsandf.WebReaper -c Release -o out --no-restore

    - name: Push to GitHub Package Repository
      run: dotnet nuget push "./out/Gsandf.WebReaper.${{github.event.release.tag_name}}.nupkg"
